### ISSUE TITLE
Crash after importing gpx file and saving

### ISSUE THREAD

**Issue by z3ntu** [openstreetmap/merkaartor#186]
Using the latest commit from git master.

Backtrace:
```
#0  0x00005555556417aa in Layer::getDisplaySize (this=0x55555808edb0) at Layers/Layer.cpp:375
#1  0x00005555555b2c31 in Document::toXML (this=0x555556188e60, stream=..., asTemplate=false, progress=0x7fffffffc620) at common/Document.cpp:208
#2  0x00005555557e64b6 in MainWindow::doSaveDocument (this=0x7fffffffd9a0, file=0x7fffffffc6b0, asTemplate=false) at MainWindow.cpp:3184
#3  0x00005555557e694a in MainWindow::saveDocument (this=0x7fffffffd9a0, fn=...) at MainWindow.cpp:3206
#4  0x00005555557e6226 in MainWindow::on_fileSaveAction_triggered (this=0x7fffffffd9a0) at MainWindow.cpp:3164
#5  0x0000555555819981 in MainWindow::qt_static_metacall (_o=0x7fffffffd9a0, _c=QMetaObject::InvokeMetaMethod, _id=40, _a=0x7fffffffc8e0) at debug/moc_MainWindow.cpp:775
#6  0x000055555581ac91 in MainWindow::qt_metacall (this=0x7fffffffd9a0, _c=QMetaObject::InvokeMetaMethod, _id=40, _a=0x7fffffffc8e0) at debug/moc_MainWindow.cpp:974
#7  0x00007ffff57643bd in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff632fe23 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff6332524 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff64bb283 in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff64c2adc in ?? () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff64c3b23 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff6379426 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff64c617c in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff6336485 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff633fbfc in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff5738782 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff633ecdb in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff6395f78 in ?? () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff6398524 in ?? () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff6336485 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff633f9b1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff5738782 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#24 0x00007ffff5d172a4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#25 0x00007ffff5d18b5b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#26 0x00007ffff5cf268c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#27 0x00007fffeed0009c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#28 0x00007ffff0a0190f in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#29 0x00007ffff0a03869 in ?? () from /usr/lib/libglib-2.0.so.0
#30 0x00007ffff0a038ae in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#31 0x00007ffff5790263 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff57373ac in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#33 0x00007ffff573f056 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#34 0x00005555557cec05 in main (argc=1, argv=0x7fffffffdbb8) at Main.cpp:241
```
I can reproduce every time after importing the gpx in the following zip (GitHub doesn't like .gpx files): [broken.zip](https://github.com/openstreetmap/merkaartor/files/3318319/broken.zip)

**Comment by mmd-osm** [comment]
That's not the only crash for this file, if you import the file, then double click on broken.gpx in the layers tab, merkaartor crashes with:

```
#0  0x0000555555627c28 in TrackSegment::duration() const ()
#1  0x000055555562c733 in TrackLayer::toHtml() ()
#2  0x00005555557102fe in LayerDock::mousePressEvent(QMouseEvent*) ()
#3  0x00007ffff5de698f in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff5ec97c3 in QDockWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff5da782c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff5daf64f in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff485a9a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff5dae622 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff5e0114b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff5e037ba in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff5da782c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff5daf0f4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff485a9a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff55eb523 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#15 0x00007ffff55ecff5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff55c42eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#17 0x00007fffdea411c0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#18 0x00007fffebb5a317 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fffebb5a550 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fffebb5a5dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#21 0x00007ffff48b38ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff48589ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff4861a84 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00005555555a8009 in main ()
```
