### ISSUE TITLE
Segfault on merging virtual node with existing node

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#48]
Segfault on merging virtual node with existing node (by moving virtual node to existing node position).
(gdb) backtrace
```
#0  0x0000000000cbf810 in ?? ()
#1  0x00000000004ccbd6 in Way::pixelDistanceNode (this=0x2b1f220, Target=..., 
    ClearEndDistance=7.0099999999999998, theView=0xd56dc0, NoSnap=..., 
    NoSelectVirtuals=false) at Features/Way.cpp:599
#2  0x00000000005acb68 in Interaction::updateSnap (this=0x2b46c30, event=
    0x7fffffffd070) at Interactions/Interaction.cpp:278
#3  0x000000000066c7c6 in MainWindow::eventFilter (this=0x7fffffffd860, event=
    0x7fffffffd070) at MainWindow.cpp:851
#4  0x00007ffff2beb886 in QCoreApplicationPrivate::sendThroughObjectEventFilters (this=this@entry=0xabda60, receiver=receiver@entry=0xd56dc0, 
    event=event@entry=0x7fffffffd070) at kernel/qcoreapplication.cpp:1065
#5  0x00007ffff346c46c in QApplicationPrivate::notify_helper (
    this=this@entry=0xabda60, receiver=receiver@entry=0xd56dc0, 
    e=e@entry=0x7fffffffd070) at kernel/qapplication.cpp:4566
#6  0x00007ffff347310f in QApplication::notify (this=<optimized out>, 
    receiver=0xd56dc0, e=0x7fffffffd070) at kernel/qapplication.cpp:4113
#7  0x00007ffff2beb71d in QCoreApplication::notifyInternal (this=
    0x7fffffffd810, receiver=receiver@entry=0xd56dc0, 
    event=event@entry=0x7fffffffd070) at kernel/qcoreapplication.cpp:955
#8  0x00007ffff347276f in sendEvent (event=<optimized out>, 
    receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#9  QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0xd56dc0, 
    event=event@entry=0x7fffffffd070, alienWidget=alienWidget@entry=0xd56dc0, 
    nativeWidget=nativeWidget@entry=0x7fffffffd860, 
    buttonDown=buttonDown@entry=0x7ffff3f91538 <qt_button_down>, 
    lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:3178
#10 0x00007ffff34e9432 in QETWidget::translateMouseEvent (
    this=this@entry=0x7fffffffd860, event=event@entry=0x7fffffffd3d0)
    at kernel/qapplication_x11.cpp:4540
#11 0x00007ffff34e7e2c in QApplication::x11ProcessEvent (this=0x7fffffffd810, 
    event=event@entry=0x7fffffffd3d0) at kernel/qapplication_x11.cpp:3663
#12 0x00007ffff3510ed2 in x11EventSourceDispatch (s=0xac01e0, callback=0x0, 
    user_data=0x0) at kernel/qguieventdispatcher_glib.cpp:146
#13 0x00007fffea5cdc5d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007fffea5cdf48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007fffea5cdffc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff2c1ad1d in QEventDispatcherGlib::processEvents (this=0xaa2e20, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:425
#17 0x00007ffff3510f96 in QGuiEventDispatcherGlib::processEvents (
    this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#18 0x00007ffff2bea271 in QEventLoop::processEvents (this=this@entry=
    0x7fffffffd7b0, flags=...) at kernel/qeventloop.cpp:149
#19 0x00007ffff2bea5d5 in QEventLoop::exec (this=this@entry=0x7fffffffd7b0, 
    flags=...) at kernel/qeventloop.cpp:204
#20 0x00007ffff2bf0059 in QCoreApplication::exec ()
    at kernel/qcoreapplication.cpp:1227
#21 0x0000000000666c20 in main (argc=1, argv=0x7fffffffe348) at Main.cpp:301
```
core dump: https://app.box.com/s/k56n2ibnj2xdizgrsryhu5f7zhvnfpq2
Generated with warning: Memory read failed for corefile section, 8192 bytes at 0x7ffff7ffa000

**Comment by Krakonos** [comment]
Hi! Could you try e860665d9e62f8d2b607fb8c453dcb129663d63e? I've done some investingation and removed a lot of similar bugs (although I wasn't able to reproduce this code path exactly).

**Comment by Krakonos** [comment]
I think it's fixed already, as I haven't encountered it in a long time. Please, reopen this bug if it's still present in current git version.
