### ISSUE TITLE
Segfault on ?

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#62]
I was just moving viewpoint while drawing line.  I had already moved the viewpoint several times during drawing that line. No additional clicks were made during moving. 

Backtrace:
```
#0  0x0000040000000005 in ?? ()
#1  0x0000000000493f20 in MemoryBackend::purge (this=0xa8e5a0 <g_backend>)
    at Backend/MemoryBackend.cpp:394
#2  0x0000000000493fc9 in MemoryBackend::resumeDeletes (this=0xa8e5a0 <g_backend>)
    at Backend/MemoryBackend.cpp:406
#3  0x00000000004ff53d in RenderTile::operator() (this=0x36556a8, theTile=...)
    at Layers/OsmRenderLayer.cpp:109
#4  0x00000000005018d1 in QtConcurrent::MapKernel<QList<QPoint>::iterator, RenderTile>::runIteration (this=0x3655670, it=...)
    at /usr/include/qt4/QtCore/qtconcurrentmapkernel.h:73
#5  0x0000000000501955 in QtConcurrent::MapKernel<QList<QPoint>::iterator, RenderTile>::runIterations (this=0x3655670, sequenceBeginIterator=..., beginIndex=28, 
    endIndex=29) at /usr/include/qt4/QtCore/qtconcurrentmapkernel.h:82
#6  0x0000000000501de9 in QtConcurrent::IterateKernel<QList<QPoint>::iterator, void>::forThreadFunction (this=0x3655670)
    at /usr/include/qt4/QtCore/qtconcurrentiteratekernel.h:263
#7  0x0000000000501ad6 in QtConcurrent::IterateKernel<QList<QPoint>::iterator, void>::threadFunction (this=0x3655670)
    at /usr/include/qt4/QtCore/qtconcurrentiteratekernel.h:225
#8  0x00007ffff2ac6bed in QtConcurrent::ThreadEngineBase::run (this=0x36556b0)
    at concurrent/qtconcurrentthreadengine.cpp:264
#9  0x00007ffff2ac8be0 in QThreadPoolThread::run (this=0x7fffbc00b430)
    at concurrent/qthreadpool.cpp:108
#10 0x00007ffff2ad586f in QThreadPrivate::start (arg=0x7fffbc00b430)
    at thread/qthread_unix.cpp:352
#11 0x00007ffff28440a4 in start_thread (arg=0x7fffc0ff9700) at pthread_create.c:309
#12 0x00007ffff1d5607d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
core: https://app.box.com/s/etitabifo6s4q8bszm3clhirxpd3f4vs

Core generated with warning: Memory read failed for corefile section, 8192 bytes at 0x7ffff7ff8000.
Built upon commit e860665d9e62f8d2b607fb8c453dcb129663d63e

**Comment by Krakonos** [comment]
Same problem as #64 .
