### ISSUE TITLE
Segfault in undo list

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#63]
This editing session was created by loading a saved file.
Crash occurred after moving just created node that was part of a new way. 
That particular node did not want to move well. By moving it, it just did not move or did not move along all the way.

backtrace:
```
#0  0x0000000002bba930 in ?? ()
#1  0x000000000058487f in CommandHistory::buildUndoList (this=0x2bc36f0, theList=
    0x10ab430) at Commands/Command.cpp:442
#2  0x00000000005ce250 in DirtyDock::updateList (this=0xff0f20)
    at Docks/DirtyDock.cpp:78
#3  0x00000000006a9d06 in DirtyDock::qt_static_metacall (_o=0xff0f20, 
    _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffca40)
    at debug/moc_DirtyDock.cpp:60
#4  0x00007ffff2bf538c in QMetaObject::activate (sender=0x1047df0, 
    m=<optimized out>, local_signal_index=<optimized out>, argv=0x0)
    at kernel/qobject.cpp:3567
#5  0x00000000006a3f7f in Document::historyChanged (this=0x1047df0)
    at debug/moc_Document.cpp:139
#6  0x0000000000454798 in Document::addHistory (this=0x1047df0, aCommand=0x28ad890)
    at common/Document.cpp:341
#7  0x00000000005b16a5 in MoveNodeInteraction::snapMouseReleaseEvent (
    this=0x2bbe110, event=0x7fffffffd230, Closer=0x0)
    at Interactions/MoveNodeInteraction.cpp:238
#8  0x00000000005af07f in FeatureSnapInteraction::mouseReleaseEvent (this=
    0x2bbe110, event=0x7fffffffd230) at Interactions/Interaction.cpp:378
#9  0x000000000047fd49 in MapView::mouseReleaseEvent (this=0xd73500, 
    anEvent=0x7fffffffd230) at common/MapView.cpp:707
#10 0x00007ffff34b7af8 in QWidget::event (this=0xd73500, event=0x7fffffffd230)
    at kernel/qwidget.cpp:8775
#11 0x00007ffff34617bc in QApplicationPrivate::notify_helper (
    this=this@entry=0xad5fb0, receiver=receiver@entry=0xd73500, 
    e=e@entry=0x7fffffffd230) at kernel/qapplication.cpp:4570
#12 0x00007ffff346843f in QApplication::notify (this=<optimized out>, 
    receiver=0xd73500, e=0x7fffffffd230) at kernel/qapplication.cpp:4113
#13 0x00007ffff2be036d in QCoreApplication::notifyInternal (this=0x7fffffffd9d0, 
    receiver=receiver@entry=0xd73500, event=event@entry=0x7fffffffd230)
    at kernel/qcoreapplication.cpp:955
#14 0x00007ffff3467a9f in sendEvent (event=<optimized out>, 
    receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#15 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0xd73500, 
    event=event@entry=0x7fffffffd230, alienWidget=alienWidget@entry=0xd73500, 
    nativeWidget=nativeWidget@entry=0x7fffffffda20, 
    buttonDown=buttonDown@entry=0x7ffff3f8c5a8 <qt_button_down>, 
    lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:3178
#16 0x00007ffff34e1832 in QETWidget::translateMouseEvent (
    this=this@entry=0x7fffffffda20, event=event@entry=0x7fffffffd590)
    at kernel/qapplication_x11.cpp:4546
#17 0x00007ffff34e022c in QApplication::x11ProcessEvent (this=0x7fffffffd9d0, 
    event=event@entry=0x7fffffffd590) at kernel/qapplication_x11.cpp:3663
#18 0x00007ffff35092d2 in x11EventSourceDispatch (s=0xad8720, callback=0x0, 
    user_data=0x0) at kernel/qguieventdispatcher_glib.cpp:146
#19 0x00007fffea015c3d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fffea015f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fffea015fcc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff2c0f98d in QEventDispatcherGlib::processEvents (this=0xaa6db0, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:425
#23 0x00007ffff3509396 in QGuiEventDispatcherGlib::processEvents (
    this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#24 0x00007ffff2bdeec1 in QEventLoop::processEvents (this=this@entry=
    0x7fffffffd970, flags=...) at kernel/qeventloop.cpp:149
#25 0x00007ffff2bdf225 in QEventLoop::exec (this=this@entry=0x7fffffffd970, 
    flags=...) at kernel/qeventloop.cpp:204
#26 0x00007ffff2be4ca9 in QCoreApplication::exec ()
    at kernel/qcoreapplication.cpp:1227
#27 0x0000000000669614 in main (argc=1, argv=0x7fffffffe388) at Main.cpp:309

```

core: https://app.box.com/s/o2s2rv8qyto539ddsuy3q8erfxqsup1e

**Comment by RM87** [comment]
Found a savefile that was created just before adding that node. https://app.box.com/s/uo6fd98f3xgdqaz6x65ihjh4lfw8jlz0

On first try I was unable to recreate that segfault.
On second try I stumbled upon something different: #64

**Comment by Krakonos** [comment]
It's possibly fixed by dd2b781c8aa99464528e284ee80a44caa67269a8, although I haven't reproduced it exactly (found with address sanitizer). Could you report if it happens again?

**Comment by RM87** [comment]
This seems to be ok now.

**Comment by RM87** [comment]
Too early closing. aprox 5 times to move the node and it happened again.
Worked fine with qt5 several times (might be just luck)
crash with qt4 on second try.

**Comment by RM87** [comment]
At least that one  I was not able to reproduce anymore.

**Comment by Krakonos** [comment]
I investigated further and managed to reproduce & fix a problem in 99deb7279a58d387cba98669feff7a9fc576f194. I was definitely the cause in my case; could you check it on your end?

**Comment by RM87** [comment]
99deb72 seems to have resolved it. Works fine with qt4 & 5.

**Comment by stephan75** [comment]
@Krakonos ... by the way:
can you estimate when you will be able to offer a new testing release (at least for Windows systems) in order to check all fixes so far by us?

**Comment by Krakonos** [comment]
I'll make one today afternoon, and post it to the mailing list.
